### PR TITLE
Apa102 PR

### PR DESCRIPTION
**Pull request by Duckle29**
Hi there.

There was a good bit of changes I couldn't request on your PR, because it was changes to files you hadn't changed and moving files around.

I'll open a PR against your fork instead :)

The changes are:

- Tie APA102 driver support into the make system so it can easily be used in place of ws2812
- Overwrite the default ws2812 driver binding with apa102 binding if apa102 driver is used
- Document the new options
- Add onekey example keymap (for proton-c and elite-c)

### CODE REVIEW

**Comment by Duckle29** [comment]
This has been tested and works on a proton-c :)

**Comment by Duckle29** [comment]
Oh and I'm not sure about changing the multiple calls of `SEND_BIT` and `SEND_BYTE`  to loops. If it's some optimization technique I'm not aware of let me know and I'll undo that :)

**Comment by Duckle29** [comment]
It should be noted that the delay is meassured at slightly over 200ns on AVR, however on ARM it's ~20us with no delay, which is slow enough to be seen. I'll be testing your your latest commit :)

**Comment by Duckle29** [comment]
Latest push implements a shaved down version of your wait macro.
After a bit of back and forth with someone more experienced with ARM, I decided to go for this shaved down version. The decision was made as the function is in no way accurate (but it doesn't have to be) and as such shouldn't be named in a way that suggests it is.

It was also shaved down to avoid conflicting with defines from ws2812 leds, in case anyone ever runs ws2812s and apa102s on the same board. This gives me ~70 ns delay on a proton-c (stm32f303)
image

**Comment by aldehir** [comment]
I can't believe I didn't see this until now. I will try out your updates and get back to you, they look promising. Thanks!

**Comment by aldehir** [comment]
@Duckle29 It looks like the upstream repo force pushed to the develop branch so the commit history is all over the place. I cannot merge in your PR with my branch because of this, but I have cherry-picked your changes onto my branch.

bf249d6600770bbb2fb66b26f3495ac40f687c9f Experimental APA102 support on AVR and ARM
59268876bd08d7a53d149c80497dbb6da3364339 Implement io_wait function for ARM

I appreciate the Makefile updates. It looks like the qmk repo split the driver from the enable option, so I did the same to your changes.

I see you moved the driver to the `quantum/` directory. I don't feel like that is an appropriate place for these drivers, I think it should stay under `drivers/`. I wonder what other people have to think about that, however.

I moved the `rgblight_call_driver()` definition to `apa102.c`. If defined in the header then someone will have multiple definitions if they include it to access the `apa102_set_brightness()` function.

I initially had unrolled my operations, which is an [optimization technique](https://en.wikipedia.org/wiki/Loop_unrolling). I mainly did it to reduce variances in the timings, although I doubt it really matters. For the `apa102_send_byte()` method I kept it unrolled, as the compiler does not automatically unroll it. For `apa102_start_frame()` I put it in a loop like you did, the compiler does automatically optimize this. You can observe this by looking at the assembly output in `.build/obj_<keyboard>_<keymap>/apa102.lst`.

I definitely like the `io_wait()` changes over what I had before. I agree with your rationale.

Take a look and let me know what you think! Overall, I'm liking these changes. I appreciate your help.

**Comment by Duckle29** [comment]
Awesome, yeah we just got ready for a `develop -> master` merge, so stuff has gone all funky. I appreciate the effort you've put in 👍 Since you've gotten the changes in I figure I'll just close this :)

**Pull request closed without merging**
